---
services:
  backend:
    image: ghcr.io/matthieuvautrin/airdrawing-back:latest
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app-network

  frontend:
    image: ghcr.io/matthieuvautrin/airdrawing-front:latest
    group_add:
      - video
    ports:
      - "8501:8501"
    devices:
      - /dev/video0:/dev/video0
    environment:
       - WEBSOCKET_URL=ws://backend:8000/ws
       - BACKEND_URL=http://backend:8000
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
